### ISSUE TITLE
Error "undefined symbol: PL_new_atom" when reading files

### ISSUE THREAD

**Issue by morxa** [yuce/pyswip#10]
When reading files, I always get the following error:

```
python3: symbol lookup error: /usr/lib64/swipl-7.2.3/lib/x86_64-linux/readutil.so: undefined symbol: PL_new_atom
```

### How to reproduce

1. Copy the following into `read.pl`

    ```
    read_file(Filename, Strings) :-
      setup_call_cleanup(
      open(Filename, read, Stream),
      read_stream_string(Stream, Strings),
      close(Stream)
    ).
    
    read_stream_string(Stream, Strings) :-
      read_line_to_string(Stream, String),
      ( String == end_of_file -> Strings = []
      ;
        read_stream_string(Stream, RStrings),
        Strings = [String|RStrings]
      ).
    ```
1. Copy the following to `read.py`:
    ```
    from pyswip.prolog import Prolog
    from pyswip.core import *
    
    prolog = Prolog()
    prolog.consult('read.pl')
    list(prolog.query('read_file("read.pl", S)'))
    ```
1. Run `python3 read.py`, which will produce the output:
    ```
    python3: symbol lookup error: /usr/lib64/swipl-7.2.3/lib/x86_64-linux/readutil.so: undefined symbol: PL_new_atom
    ```

### Workaround
`PL_new_atom` is defined in `libswipl.so`, but `readutil.so` is not linked against `libswipl`. As a workaround, `libswipl.so` can be `LD_PRELOAD`ed:
```
$ export LD_PRELOAD=/usr/lib64/swipl-7.2.3/lib/x86_64-linux/libswipl.so.7.2.3
$ python3 read.py
```

After preloading the shared lib, the error disappears (and #9 occurs). This show that this is indeed a problem with linking.

I'm not sure if this is an error on the pyswip side or the swipl side, but I assume if you always load `libswipl.so`, then the error will disappear.

This is on Fedora 25 with SWi-Prolog 7.2.3.

**Comment by jannikb** [comment]
I had a similiar issue while loading the odbc library on ubuntu 16.04 and swi-prolog 7.6.4:
```'$open_shared_object'/3: /usr/lib/swi-prolog/lib/amd64/odbc4pl.so: undefined symbol: PL_get_long```

The workaround with `LD_PRELOAD` also worked for me with an adjusted path:
```export LD_PRELOAD=/usr/lib/libswipl.so```

**Comment by yuce** [comment]
Thanks @morxa. The test case you provided was very useful. Passing `mode=RTLD_GLOBAL` to library loader fixed this issue.
