### ISSUE TITLE
Deploying PySwip on Heroku

### ISSUE THREAD

**Issue by steven-tey** [yuce/pyswip#114]
Thanks a lot for building such an awesome SWI-Prolog bridge for Python! Quick question – I'm building a Python-Flask-Prolog app for my school assignment and everything works perfectly locally, but when I try to deploy it to Heroku I get the following error:

```
ImportError: Could not find the SWI-Prolog library in this platform. If you are sure it is installed, please open an issue.
```

I've tried everything from changing the paths of the functions in the `core.py` file to manually installing `swipl` in the bin folder of my venv but nothing is working :( 

Please help! Thank you so much in advance!

**Comment by gregorywoolery** [comment]
Any improvement or news on this ?

**Comment by yuce** [comment]
Note to the future:
The latest version of PySwip should work without any extra work as long as the correct version of SWI-Prolog is installed.
See: https://pyswip.readthedocs.io/en/stable/get_started.html
