### ISSUE TITLE
Multithreading in Pyswip

### ISSUE THREAD

**Issue by ShubhamSharma1808** [yuce/pyswip#120]
On accessing pyswip in a thread it gives segmentation fault in Linux(Ubuntu) and memory violation in Windows.
if there is some way to achieve multithreading in pyswip please help

**Comment by stuz5000** [comment]
That's the expected behavior from libswipl.
You need to create a new engine for each thread.

**Comment by stuz5000** [comment]
It's only a concept in the C API -  pyswip has only wrapped a subset of
those functions in swipl.

You’d need to identify those APIs and wrap the with ctypes annotations (as
pyswip does).
You could copy the method pyswip does for the new engine functions (but
following the code to where it calls PL_blahblah(  ... ) and copy the
pattern)  and use it in your local code, or someone could submit a PR.

**Comment by ShubhamSharma1808** [comment]
In the open Issue#3, I found the solution. it worked for me.
here's the [link](https://github.com/yuce/pyswip/issues/3#issuecomment-355458825) for that.
