### ISSUE TITLE
Powered by PySwip

### ISSUE THREAD

**Issue by devdaniellima** [yuce/pyswip#128]
Hello, I'm developing a project for an inference engine for the WSML language, I used your library to be able to create reasoning using Prolog. From this project, an article and a monograph are being developed for my university.

The project can be found at the link below:
https://github.com/devdaniellima/midsi
Solution for data discovery in applications applicable to the Semantic Web, enabling the loading of ontology and inference of results using the WSML language.

Thank you very much for the tool, without it I would not have been able to carry out the project.

**Comment by yuce** [comment]
Hi Daniel, thanks a lot for sharing this. I've added the project to the README. Could you let me know when the article is out? I would like to add that too to the README if that's OK.

**Comment by devdaniellima** [comment]
Of course Yuce. When the article is ready I notice you.
