### ISSUE TITLE
Error with SWI-Prolog v8.5.3 and pyswipl 0.2.10

### ISSUE THREAD

**Issue by andrewcropper** [yuce/pyswip#136]
@hakank has identified a problem with Error with SWI-Prolog v8.5.3 and pyswipl 0.2.10:

https://github.com/logic-and-learning-lab/Popper/issues/28#issuecomment-995588199

It crashes when running any examples

**Comment by yuce** [comment]
For anyone coming to this issue from the future.
The latest version [v0.3.0](https://github.com/yuce/pyswip/releases/tag/v0.3.0) should fix this problem.
Please feel to reopen the issue if the the problem persists.

**Comment by Guthur** [comment]
@yuce Can you provide anymore details on how this was resolved?

I've ran into a similar segv on `PL_advance_hash_table_enum()` but have struggled to reproduce in the context I've encountered it.

Thanks
