### ISSUE TITLE
pip pyswip version low

### ISSUE THREAD

**Issue by w4n9H** [yuce/pyswip#14]
pip install pyswip
from pyswip import *
SWI-Prolog not installed as a shared library. Install SWI-Prolog (5.6.34 works just fine)
core.py not use  find_library
use github code success

**Comment by A-deLuna** [comment]
I think the version on pip is 2.2

**Comment by yuce** [comment]
I've pushed an updated version to PyPI: https://pypi.org/project/pyswip/
