### ISSUE TITLE
Please provide support for M1 Macs

### ISSUE THREAD

**Issue by AmrSol** [yuce/pyswip#142]
Hi Yuce,

It is impossible to run pyswip on M1 architecture (more specifically I have the M1 Pro). I have tried every combination of python SWI-PROLOG and pyswip versions to no avail. 

It would be **highly** appreciated if you offered support for M1 arm64 architecture. SWI-Prolog is working on a Beta for it.

Kindest regards,
Amr

**Comment by yuce** [comment]
Hi @AmrSol a contributor updated https://github.com/yuce/pyswip/blob/master/INSTALL.md#macos-m1 for M1 Macs.

**Comment by AmrSol** [comment]
Thank you so much @yuce. Works like a charm. =)
