### ISSUE TITLE
Redefined static procedure after clearing Prolog() object

### ISSUE THREAD

**Issue by deRemo** [yuce/pyswip#156]
I'm using pyswip in a python script very similar to this one:
```py
for path in plpaths:
    prolog = Prolog()
    prolog.consult(path)

    prolog.query(...)
[...]
```
The consulted files include a 'global' pl file shared by everyone.
I'm encountering this problem when `len(plpaths) > 1`:

```
Warning: /path/to/included/file.pl:5:
Warning:    Redefined static procedure pred/3
Warning:    Previously defined at /path/to/included/file.pl:5
[...]
```

I tried cleaning up the prolog variable (`prolog = None` and `del prolog`), but didn't work. I tried re-importing the module at each iteration, but nothing. Is there a fix for this?

**Comment by femartip** [comment]
Had the same problem. It seems that the Prolog() object is a singleton and so it is created in the module level. However I have seen that pywip_notebook creates a wrapper around the Prolog class so it creates the Prolog instance in its own module. I am trying with this.

**Comment by yuce** [comment]
As @femartip  pointed out, `Prolog` acts like a singleton. There is no way to initialize to different `Prolog` instances, this is a constraint of SWI-Prolog.

But this problem seems to be easily solved using `multifile/1`:
https://www.swi-prolog.org/FAQ/Multifile.md
```
$ cat pl1.prolog
:- multifile pred/1.
pred(p1).

$ cat pl2.prolog 
:- multifile pred/1.
pred(p2).

$ cat prog.py
from pyswip import Prolog

pl_paths = ["pl1.prolog", "pl2.prolog"]
for path in pl_paths:
    Prolog.consult(path)
for item in Prolog.query("pred(A)"):
    print(item)

$ python3 prog.py
{'A': 'p1'}
{'A': 'p2'}
```

**Comment by yuce** [comment]
Closing this issue for now, but please feel free to reopen it if necessary.

**Comment by deRemo** [comment]
Hi Yuce,

Thanks for your response!

I actually switched to swiplserver after encountering this issue and finished the project with that one, but today I tried multifile as you suggested on my pyswip-based scripts...and it worked perfectly, thanks!. I'll probably use it for the extension of this [paper](https://www.scitepress.org/Papers/2024/127295/127295.pdf)

**Comment by yuce** [comment]
Hi Remo,

Very interesting paper, thanks for linking!
Looking forward to the extension paper.
