### ISSUE TITLE
Powered by Pyswip

### ISSUE THREAD

**Issue by NicolasLeidi** [yuce/pyswip#158]
Hello, I'm developing a project for my university, an application to allow teachers to create tests for PROLOG problems and projects for academic purpose, and allowing the students to test their solutions easily and get better feedback.

The project can be found at this link:
[https://github.com/NicolasLeidi/Trabajo-Final](url)

Thank you so much for the tool, I would not be able to develop such project without this library.

**Comment by yuce** [comment]
Hi Nicolas,

That's very cool! Thanks for informing about your project and your kind words.
I've added it to the README.
