### ISSUE TITLE
Problem with Path and older version of SWI-Prolog in Windows

### ISSUE THREAD

**Issue by lmatera19** [yuce/pyswip#193]
I'm encountering the following problems while using PySWIP 0.3.2:

### 1. Problem with the `consult` method on Windows
When trying to use the `consult` method with the following code:

```python
from pyswip import Prolog
from pathlib import Path

rules_file = Path("../kb/rules.pl")
prolog = Prolog()
prolog.consult(rules_file)
```

I get this error:

```
pyswip.prolog.PrologError: Caused by: 'consult('../kb/rules.pl')'. Returned: 'error(syntax_error(undefined_char_escape(k)), string(b"consult('..\\kb\\rules.pl') . ", 11))'.
```

It seems the issue is caused by the `Path` class converting the file path into a `WindowsPath` object. A possible solution is to modify line 393 in `prolog.py` as follows:

```python
next(cls.query(str(path.as_posix()).join(["consult('", "')"]), catcherrors=catcherrors))
```

This ensures the file path is converted to a POSIX-style string. I tested this solution with an older version of the library, passing `str(rules_file.as_posix())` and it resolved the issue.

### 2. Compatibility with older SWI-Prolog versions
I don't know if the library has to be backward compatible, but I'm using an older version of SWI-Prolog (v8.4.2) and the library couldn't find the installation path because the necessary registry key was missing.

**Comment by lmatera19** [comment]
I have cloned the project, create a new branch and commit the fix but i can not push the commit. It says 

> Permission to yuce/pyswip.git denied to lmatera19.

**Comment by yuce** [comment]
You must first fork the project.
Then you can create a branch in your own fork with the changes.
Github will then offer to create a PR using your branch.
