### ISSUE TITLE
Can not find SWI-Prolog installed in ubuntu

### ISSUE THREAD

**Issue by rylanchiu** [yuce/pyswip#35]
When I change the [code](https://github.com/yuce/pyswip/blob/master/pyswip/core.py#L85) to `cmd = Popen(['swipl', '--dump-runtime-variables'], stdout=PIPE)`, it works.

**Comment by PaulBrownMagic** [comment]
Same on CentOS, also a linux one.

**Comment by alvarogunawan** [comment]
Ran into the same problem and fixed it the same way as @rylanchiu. I'm using the following environment:

- Ubuntu 16.04.5 LTS
- SWI-Prolog version 8.0.1
- Python 3.5.2
- SWI-Prolog was installed through the package manager as described here: http://www.swi-prolog.org/build/PPA.html

Hope this helps

**Comment by JoelBender** [comment]
Similar problem, Ubuntu 16.04, SWI-Prolog version 8.0.1 for x86_64-linux, I found the `.so` file in the `/usr/lib` directory.  I fixed it by creating a local `lib` directory and symlinking:
```
    $ mkdir lib
    $ pushd lib
    $ ln -s /usr/lib/swi-prolog/lib/x86_64-linux/libswipl.so .
    $ popd
```
I noticed that when importing like `from pyswip import Prolog` the usage message like `1) swipl [options] prolog-file ... [-- arg ...]` is printed out.  I'm obviously just starting out, but this is going to be awesome... :-)

**Comment by yuce** [comment]
Fixed by https://github.com/yuce/pyswip/pull/44
