### ISSUE TITLE
Right output on console but wrong by pyswip.query()

### ISSUE THREAD

**Issue by rylanchiu** [yuce/pyswip#36]
I am using pyswip to play with [geoquery dataset](http://www.cs.utexas.edu/users/ml/nldata/geoquery.html).  

```
In [1]: from Prolog import prolog

In [2]: prolog.consult('geobase')
In [3]: prolog.consult('geoquery')
In [4]: list(prolog.query('answer(A,(river(A),loc(A,B),const(B,stateid(california)))).'))
```

It can get right result with prolog but weired output with pyswip:

```
Answer = [colorado]
Out[71]: [{'A': Variable(68), 'B': Variable(71)}] 
```

**Comment by hits-nlp** [comment]
I'm having a very similar issue, with a 'findall' query working correctly when called in the PL console, but returning a list of atoms instead of values when called from pyswip: 

 {'PROFILE': [Atom('7248900'), Atom('7249412'), Atom('7249796')]}

Has there been any progress on this?

**Comment by hits-nlp** [comment]
OK, got it, it has to to with how Atoms are rendered by Python when submitted to print()...

**Comment by hits-nlp** [comment]
I did the following mod to easy.py
    def __repr__(self):
        return str(self.chars.decode("utf-8"))
#        return str(self.handle).join(["Atom('", "')"])

Now the above query returns
{'PROFILE': [conf_cscw_jeffaylmss92, conf_ht_shackelfordss93, conf_ht_smiths91]}

**Comment by hits-nlp** [comment]
I modified easy.py as follows:
    def __repr__(self):
        return str(self.chars.decode("utf-8"))

Now the above query returns:

{'PROFILE': [conf_cscw_jeffaylmss92, conf_ht_shackelfordss93, conf_ht_smiths91]}

**Comment by yuce** [comment]
@hits-nlp The updated code for pyswip is at: https://github.com/yuce/pyswip/tree/refactor It is currently missing (a lot of) things, but the working parts should be more robust. Depending on your use case, it may work better.
