### ISSUE TITLE
what features are missing?

### ISSUE THREAD

**Issue by bbferka** [yuce/pyswip#45]
Hi @yuce, 

Glad to see that this project is still active! I used it briefly a couple of years back. I am wondering, what does "incomplete" stand for in the description of the project? Is there a list somewhere of missing features or a description of what is currently not possible with pyswip? I am thinking of using it in a bigger project, but would be nice to know beforehand the missing features. 

Cheers!

**Comment by yuce** [comment]
Hi @bbferka,

Unfortunately there is not a list of missing features. You may check the examples and tests to see what's working. You may also want to check https://github.com/yuce/pyswip/tree/refactor which is even more incomplete, but the code quality there should be better.

**Comment by nicoabie** [comment]
@yuce I can't find the refactor branch, was it merged?

**Comment by yuce** [comment]
@nicoabie The refactor branch is removed for the time being.
