### ISSUE TITLE
Segfault when the query variable should be a list

### ISSUE THREAD

**Issue by moqingyan** [yuce/pyswip#51]
I am working on the Mac OS system with the following setting:
- SWI-Prolog version 7.6.4 for x86_64-darwin18.2.0
- pyswip build from source using the refactor branch

I am consulting the file: test_list.pl
```

incr(X, X1) :-
    X1 is X + 1.

get_list(0, []).

get_list(N1, [N1|Ls]):- 
    get_list(N, Ls),
    incr(N, N1).

```
and try to fetch the result for get list in python: 
```
from pyswip import Prolog
prolog = Prolog()
prolog.consult("test_list.pl")
solu = prolog.query("get_list(3, X)")
for i in solu:
    print (i)
    break
```
The result I got is:
```
python spec_verify.py
{'X': [3, 2, 1]}
fish: 'python spec_verify.py' terminated by signal SIGSEGV (Address boundary error)
```

Any help is appreciated!

**Comment by yuce** [comment]
You can pass `maxresult=1` to retrieve only a single answer, like:
```
solu = prolog.query("get_list(3, X)", maxresult=1)
```

**Comment by moqingyan** [comment]
But this does not help solve the segfault though. It seems the segfault occurs at some clean up stage:
```
from pyswip import *

prolog = Prolog()
prolog.consult("test_list.pl")

solu = prolog.query("get_list(3, X)", maxresult=1)
for s in solu:
    print(s)
    break

print(s['X'][1])
print("prog end")
```
The corresponding output is:
```
{'X': [3, 2, 1]}
2
prog end
fish: 'python spec_verify.py' terminated by signal SIGSEGV (Address boundary error)
```
If I change to bash:
```
{'X': [3, 2, 1]}
2
prog end
Segmentation fault: 11
```

**Comment by yuce** [comment]
Can you remove the `break` in the loop and try again?

**Comment by moqingyan** [comment]
The program either stuck or quit unexpectedly. The terminal window closed itself when the program quits.

**Comment by yuce** [comment]
This is the code I've tried:
```
from pyswip import Prolog                                             
prolog = Prolog()
prolog.consult("test_list.pl")
solu = prolog.query("get_list(3, X)", maxresult=1)
for i in solu:
    print (i)
```
This is what I get when running it:
```
$ python test_list.py                       
{'X': [3, 2, 1]}
$
```
No segfaults, etc. (of course that doesn't rule out a bug in PySwip). This is on Ubuntu 18.04, Python 3.6.8, SWI 7.6.4. All of those using Ubuntu's packages.

Did you try your code using SWI-Prolog? It doesn't terminate after the first solution.

**Comment by moqingyan** [comment]
Yes, I have tried it with the SWI-Prolog and it worked normally. I think I can try to install the packages again on Ubuntu system and see whether the problem is MacOSX specific. :)

**Comment by yuce** [comment]
This is what I've tried with SWI-Prolog:
```
?- [test_list].                                                       
true.                                                                 

?- get_list(3, X).                                                    
X = [3, 2, 1] ;  <-- doesn't terminate after that
```
What do you get after `[3, 2, 1]` ?

**Comment by fpopineau** [comment]
Hi there, 
I can confirm that there is definitely some problem here. I encountered a similar situation with a segv on both Windows and MacOSX, with SWI-PL 7.6 and 8.0. I get this result on the test case:
```
$ python test_list.py
{'X': [3, 2, 1]}
Exception ignored in: <generator object Prolog._QueryWrapper.__call__ at 0x0000019B3385F580>
Traceback (most recent call last):
  File "C:\Local\PyConfig\envs\aienv\lib\site-packages\pyswip\prolog.py", line 130, in __call__
OSError: exception: access violation reading 0x0000000000000110
```
It seems that an exception occurs inside the finally clause of the call to Prolog, precisely in the call to `PL_cut_query(swipl_qid)`.
I tried to replace this call with `PL_close_query(swipl_qid)` but the result is the same.
Any idea of what can cause that ?
Regards,

**Comment by fpopineau** [comment]
More on this issue. I get a constant segfault if I run the query this way:
```
q = prolog.query("get_list(3, X)", maxresult=1)
solu = next(q)
print(solu['X'])
```
but everything is perfect if I run it this way:
```
solu = next(prolog.query("get_list(3, X)", maxresult=1))
print(solu['X'])
```
The difference is about when the  `finally` clause is called. In the later case, the `finally` clause is called before printing the term, whereas it is called after printing it int the former case.
