### ISSUE TITLE
importing pyswip goes wrong

### ISSUE THREAD

**Issue by nudelgurke** [yuce/pyswip#54]
I had some Problems setting up pyswip.

I installed the current release with the Windows installer und then used pip to installpyswip.
But when I tried to use it, I got an exeption when importing it.
It was an Index Error, while looking for the swipl installation.
So I debugged - and found out, that the code was looking for a folder named 'pl' instead of 'swipl'.
Maybe there went some letters missing accidentally? 
After renaming my folder accordingly, swipl was found.
But the I got another Error: Swipl complained, about being called with an unknown argument.
I fixed that one by changing the agrument '-nosignals' to '--signals=false'.

So, just in case, someone encounters the same problem or is inclined to fixing the code, this ist my story

**Comment by yuce** [comment]
The current release has no Windows installer. First make sure the architecture of Python and SWI-Prolog are the same (e.g., they are both 32bits or they are both 64bits) then see: https://github.com/yuce/pyswip/blob/master/INSTALL.md to how to install the latest version of PySwip.

**Comment by janeshin059** [comment]
you saved me man, thank you so much!!

**Comment by Adamxma** [comment]
For Windows
just Adjust Core.py 
change line 180 to: 
    paths = [os.path.join(programFiles, r'swipl\bin', dllName)
