### ISSUE TITLE
pyswip test error

### ISSUE THREAD

**Issue by anlanxuan** [yuce/pyswip#57]
ERROR: The system was unable to find the specified registry key or value.
on windows

**Comment by yuce** [comment]
Hi, I use Windows rarely, so not sure what's the problem is. Have you installed SWI-Prolog before PySwip?

**Comment by anlanxuan** [comment]
I have solved this problem，try to use the lower version.

**Comment by jarble** [comment]
I also see this error when I try to use pyswip on Windows.

I tried to import pyswip:

`from pyswip import Functor, Variable, Query, call`

but then I saw this error message:

```
ERROR: The system was unable to find the specified registry key or value.
Traceback (most recent call last):
  File "test_generator.py", line 1, in <module>
    from pyswip import Functor, Variable, Query, call
  File "C:\Users\jarbl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswip\__init__.py", line 29, in <module>
    from pyswip.prolog import Prolog
  File "C:\Users\jarbl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswip\prolog.py", line 28, in <module>
    from pyswip.core import *
  File "C:\Users\jarbl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswip\core.py", line 568, in <module>
    (_path, SWI_HOME_DIR) = _findSwipl()
  File "C:\Users\jarbl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswip\core.py", line 411, in _findSwipl
    (path, swiHome) = _findSwiplWin()
  File "C:\Users\jarbl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswip\core.py", line 208, in _findSwiplWin
    match = pattern.match(ret[-1])
IndexError: list index out of range
```

What might be the cause of this error?

**Comment by AlucardNosferatu** [comment]
> I have solved this problem，try to use the lower version.

Which version? I was using 8.2.4

**Comment by anlanxuan** [comment]
> > I have solved this problem，try to use the lower version.
> 
> Which version? I was using 8.2.4

Use python 3.6，SWI-Prolog 7.6.4 can run successfully

**Comment by AlucardNosferatu** [comment]
> > > I have solved this problem，try to use the lower version.
> > 
> > 
> > Which version? I was using 8.2.4
> 
> Use python 3.6，SWI-Prolog 7.6.4 can run successfully

I'll have a try, Thx!!!

**Comment by Nimrah009** [comment]
> I also see this error when I try to use pyswip on Windows.
> 
> I tried to import pyswip:
> 
> `from pyswip import Functor, Variable, Query, call`
> 
> but then I saw this error message:
> 
> ```
> ERROR: The system was unable to find the specified registry key or value.
> Traceback (most recent call last):
>   File "test_generator.py", line 1, in <module>
>     from pyswip import Functor, Variable, Query, call
>   File "C:\Users\jarbl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswip\__init__.py", line 29, in <module>
>     from pyswip.prolog import Prolog
>   File "C:\Users\jarbl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswip\prolog.py", line 28, in <module>
>     from pyswip.core import *
>   File "C:\Users\jarbl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswip\core.py", line 568, in <module>
>     (_path, SWI_HOME_DIR) = _findSwipl()
>   File "C:\Users\jarbl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswip\core.py", line 411, in _findSwipl
>     (path, swiHome) = _findSwiplWin()
>   File "C:\Users\jarbl\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pyswip\core.py", line 208, in _findSwiplWin
>     match = pattern.match(ret[-1])
> IndexError: list index out of range
> ```
> 
> What might be the cause of this error?

Than, were you able to handle this problem?

**Comment by yuce** [comment]
For anyone coming to this issue from the future.
The latest version [v0.3.0](https://github.com/yuce/pyswip/releases/tag/v0.3.0) should fix this problem.
Please feel to reopen the issue if the the problem persists.
