### ISSUE TITLE
Non-deterministic foreign functions

### ISSUE THREAD

**Issue by rmanhaeve** [yuce/pyswip#58]
Hi

Is there already support for non-deterministic foreign functions? Passing the PL_FA_NONDETERMINISTIC flag to registerForeign doesn't seem to have any impact.

Kind regards,
Robin

**Comment by yuce** [comment]
Hi Robin,

Unfortunately there is no support for non-deterministic foreign functions.

**Comment by rmanhaeve** [comment]
I have been able to get it to work. Perhaps I'll make a pull request for it soon.

**Comment by yuce** [comment]
OK, thanks!

**Comment by fpopineau** [comment]
Hi all,
@rmanhaeve : I would be very interested in your pull request :-) (or a sketch of your changes)
Regards,

**Comment by fpopineau** [comment]
Thanks a lot. Very nice and that would deserve an example in the `examples` directory.
