### ISSUE TITLE
TODO: There is a Pengines interface

### ISSUE THREAD

**Issue by JanWielemaker** [yuce/pyswip#77]
FYI, the TODO.md claims there is no Pengine interface for Python.  This is no longer true.  See https://www.swi-prolog.org/pengines/PenginesFromPython.md

I wanted to create a pull request, but then I guess you do not want resolved issues in the TODO ...

**Comment by yuce** [comment]
Hi @JanWielemaker there's no TODO.md in this project, and there is no mention of the Pengine interface anywhere. Is it possible that this issue was created in the wrong project?

**Comment by JanWielemaker** [comment]
Oops.  I forked this before and added some notes in a TODO.md file.   Getting back after a couple of years I forgot about that and thought it were your remarks ...  Sorry for the noise.  Closing.

**Comment by yuce** [comment]
No problem at all. Thanks for SWI-Prolog and starring PySwip.
