### ISSUE TITLE
Incoming variable problem

### ISSUE THREAD

**Issue by anlanxuan** [yuce/pyswip#78]
Hello, my purpose is to generate data through python and pass these data into Prolog for regular query, but I don't know how to pass these data into Prolog through pyswip for instantiation. Is there any method that can guide me?

**Comment by marekyggdrasil** [comment]
An example for creating Prolog knowledge base entries via `pyswip`

https://github.com/yuce/pyswip/blob/1ad3ce2d3fa4263273655f12bd9c4be07de2bd04/examples/father.py#L35-L37

I recommend closing this issue.
