### ISSUE TITLE
query doesn't return tuples correctly

### ISSUE THREAD

**Issue by morxa** [yuce/pyswip#8]
When the result contains tuples, it is not printed correctly.
``` python
import pyswip                                                                   
p = pyswip.Prolog()                                                             
p.assertz("parents((michael,mary),peter)")                                      
print(list(p.query("parents(X,peter)"))) 
```

This returns `[{'X': ',(michael, mary)'}]` (note the extra comma)
Expected result: `[{'X': '(michael, mary)'}]`

**Comment by yuce** [comment]
This is fixed in the rewrite/refactoring of PySwip in the `refactor` branch. E.g.,: https://github.com/yuce/pyswip/blob/refactor/tests/test_prolog.py
