### ISSUE TITLE
Tests break on current build

### ISSUE THREAD

**Issue by EricZinda** [yuce/pyswip#84]
I'm getting consistent failures on many tests in the current build.  If I back out the changes from your last commit, they are fixed.

Here's an example from tests/test_foreign.py:

ERROR: atom_chars/2: Arguments are not sufficiently instantiated
EE
======================================================================
ERROR: test_deterministic_foreign (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ericzinda/Enlistments/pyswip/tests/test_foreign.py", line 16, in test_deterministic_foreign
    prolog.assertz("father(michael,john)")
  File "/Users/ericzinda/Enlistments/pyswip/pyswip/prolog.py", line 140, in assertz
    next(cls.query(assertion.join(["assertz((", "))."]), catcherrors=catcherrors))
  File "/Users/ericzinda/Enlistments/pyswip/pyswip/prolog.py", line 126, in __call__
    raise PrologError("".join(["Caused by: '", query, "'. ",
pyswip.prolog.PrologError: Caused by: 'assertz((father(michael,john))).'. Returned: 'error(instantiation_error, context(:(system, /(atom_chars, 2)), Variable(72)))'.

======================================================================
ERROR: test_nondeterministic_foreign (__main__.MyTestCase)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ericzinda/Enlistments/pyswip/tests/test_foreign.py", line 44, in test_nondeterministic_foreign
    result = list(prolog.query("nondet(X)"))
  File "/Users/ericzinda/Enlistments/pyswip/pyswip/prolog.py", line 126, in __call__
    raise PrologError("".join(["Caused by: '", query, "'. ",
pyswip.prolog.PrologError: Caused by: 'nondet(X)'. Returned: 'error(instantiation_error, context(:(system, /($c_call_prolog, 0)), Variable(72)))'.

----------------------------------------------------------------------
Ran 2 tests in 0.003s

FAILED (errors=2)

**Comment by JeanChristopheRohner** [comment]
@EricZinda Did you find a solution to this?

**Comment by JeanChristopheRohner** [comment]
Thanks for the tip!

**Comment by kamahen** [comment]
See Issue #143 -- it appears that the problem is due to an unexpected version of SWi-Prolog being used.
pyswip can check for this using https://www.swi-prolog.org/pldoc/doc_for?object=c(%27PL_version_info%27)

**Comment by adamcrussell** [comment]
I ran into this problem (swipl 9.0.4) and the fix is to make a small change to core.py in the installed pyswipl. Details are here: https://swi-prolog.discourse.group/t/best-easiest-way-to-downgrade-to-version-8-4-3-on-linux-ubuntu-20-04/5966/9

It is odd that this small fix hasn't made it into the code yet.

**Comment by divyadk** [comment]
Thanks so much everyone! This fix is a lifesaver! (Worked on Macbook M3 Pro)

**Comment by yuce** [comment]
@divyadk @adamcrussell 
Does this issue still exist with the latest code on the `master` branch?

**Comment by yuce** [comment]
The latest version [v0.3.0](https://github.com/yuce/pyswip/releases/tag/v0.3.0) should fix this problem.
Please feel to reopen the issue if the the problem persists.
