### ISSUE TITLE
Always get None on facts with double quotes

### ISSUE THREAD

**Issue by eolandro** [yuce/pyswip#90]
this is a minimal test
Prolog
`test("hello","world").`
Python
```
R = list(prolog.query("test(A,B)"))
print(R)
```

gets
`[{'A': None, 'B': None}]`

**Comment by stuz5000** [comment]
I believe this is due to a breaking changes in SWI-Prolog.h. 
I think fixing https://github.com/yuce/pyswip/issues/92 will fix this.
Can you report which version of swi-prolog you have installed?

**Comment by stuz5000** [comment]
Resolved here: https://github.com/yuce/pyswip/pull/93

**Comment by eolandro** [comment]
SWI-Prolog version 8.2.0 for x86_64-linux

**Comment by stuz5000** [comment]
Thanks. Then it’s likely the same issue had when upgrading from 8.1 to 8.3
—- libswiprolog has changed the enum values of type contacts.
I’ve submitted a PR with a fix and test for your case. Perhaps @yuce will
accept it.

**Comment by eolandro** [comment]
Thanks i will close this issue when the fit be accepted.
PD sorry for bad english
