### ISSUE TITLE
Error while reading swipl version

### ISSUE THREAD

**Issue by claminos** [yuce/pyswip#91]
Here's what I get when I enter the SWI-Prolog version:

`(...) in get_swi_ver
    match = re.search(r'[0-9]\.[0-9]\.[0-9]')
TypeError: search() missing 1 required positional argument: 'string'`

The swipl version is the 8.2.0 but I don't think it makes any difference

**Comment by glebobinnec** [comment]
On windows 10 i had this kind of problem, pyswip was unable to load Prolog because it didn't find the SwiProlog path and i don't if it is possible to specify it...
So i modify C:\Python\Python36\Lib\site-packages\pyswip\core.py line 180 :
r'pl\bin' -> r'swipl\bin'

ciao

**Comment by yuce** [comment]
This problem should be fixed with the last version.
